import sys
import pygame
from pygame.locals import *

import Asset_Instantiation_Images as m
  
#################################################################################################################################################
#  Maps Instantiation                                                                                                                              #
#################################################################################################################################################
 
test_battle = [
            [m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST_E_GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_W_WATER_2, m.FOREST_W_GRASS, m.FOREST_SE_GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_SW_GRASS, m.FOREST, m.FOREST],
            [m.FOREST, m.FOREST, m.FOREST_S_GRASS, m.FOREST_S_GRASS, m.FOREST_S_GRASS, m.FOREST_S_GRASS, m.FOREST, m.FOREST_E_GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_W_WATER_2, m.FOREST_ESW_GRASS, m.GRASS, m.FORTRESS_NW, m.FORTRESS_NE, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_W_GRASS, m.FOREST],
            [m.FOREST, m.FOREST_E_GRASS, m.NAZCA_4, m.NAZCA_8, m.NAZCA_12, m.NAZCA_16, m.FOREST_W_GRASS, m.FOREST_E_GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_W_WATER_2, m.GRASS, m.GRASS, m.FORTRESS_SW, m.FORTRESS_SE, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_SW_GRASS, m.FOREST],
            [m.FOREST, m.FOREST_E_GRASS, m.NAZCA_3, m.NAZCA_7, m.NAZCA_11, m.NAZCA_15, m.FOREST_W_GRASS, m.FOREST_E_GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_W_WATER_2, m.GRASS, m.GRASS, m.SAND_NW_GRASS, m.SAND_NE_GRASS, m.GRASS, m.GRASS, m.WAVYSAND_NW_GRASS, m.WAVYSAND_NE_GRASS, m.GRASS, m.FOREST_W_GRASS],
            [m.FOREST, m.FOREST_E_GRASS, m.NAZCA_2, m.NAZCA_6, m.NAZCA_10, m.NAZCA_14, m.FOREST_W_GRASS, m.FOREST_E_GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_W_WATER_2, m.SAND_NW_GRASS, m.SAND_NS_GRASS, m.SAND_S_GRASS, m.SAND_SE_GRASS, m.GRASS, m.WAVYSAND_NWS_GRASS, m.WAVYSAND, m.WAVYSAND_E_GRASS, m.GRASS, m.FOREST_SW_GRASS],
            [m.FOREST, m.FOREST_E_GRASS, m.NAZCA_1, m.NAZCA_5, m.NAZCA_9, m.NAZCA_13, m.FOREST_W_GRASS, m.FOREST_E_GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_SW_WATER_2, m.SAND_EW_GRASS, m.GRASS_S_WATER_2, m.GRASS_S_WATER_2, m.GRASS_S_WATER_2, m.GRASS_S_WATER_2, m.GRASS, m.WAVYSAND_SW_GRASS, m.WAVYSAND_S_GRASS, m.WAVYSAND_NES_GRASS, m.GRASS],
            [m.FOREST, m.FOREST, m.FOREST_NE_GRASS, m.GRASS, m.GRASS, m.FOREST_NW_GRASS, m.FOREST, m.FOREST_E_GRASS, m.GRASS_E_WATER_2, m.WATER, m.WATER, m.BRIDGE_VERTICAL, m.WATER, m.WATER, m.WATER, m.WATER, m.GRASS_W_WATER_2, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS],
            [m.FOREST, m.FOREST, m.FOREST_E_GRASS, m.GRASS, m.GRASS, m.FOREST_W_GRASS, m.FOREST, m.FOREST, m.FOREST_NE_GRASS, m.GRASS_N_WATER_2, m.GRASS_N_WATER_2, m.SAND_EW_GRASS, m.GRASS_N_WATER_2, m.GRASS_N_WATER_2, m.GRASS_NE_WATER_2, m.WATER, m.GRASS_W_WATER_2, m.GRASS, m.GRASS, m.GRASS, m.FOREST_NW_GRASS, m.FOREST_N_GRASS],
            [m.FOREST, m.FOREST, m.FOREST_E_GRASS, m.GRASS, m.GRASS, m.FOREST_SW_GRASS, m.FOREST_S_GRASS, m.FOREST, m.FOREST_N_GRASS, m.FOREST_NE_GRASS, m.GRASS, m.SAND_W_GRASS, m.SAND_N_GRASS, m.SAND_NE_GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_W_WATER_2, m.GRASS, m.GRASS, m.FOREST_NW_GRASS, m.FOREST_N_GRASS],
            [m.FOREST, m.FOREST, m.FOREST_E_GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_SW_GRASS, m.FOREST, m.FOREST_E_GRASS, m.GRASS, m.SAND_W_GRASS, m.SAND, m.SAND_E_GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_SW_WATER_2, m.GRASS_S_WATER_2, m.GRASS, m.FOREST_SW_GRASS, m.FOREST_S_GRASS],
            [m.FOREST, m.FOREST, m.FOREST, m.FOREST_NE_GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_SW_GRASS, m.FOREST_SE_GRASS, m.GRASS, m.SAND_W_GRASS, m.SAND_S_GRASS, m.SAND_SE_GRASS, m.GRASS_E_WATER_2, m.WATER, m.WATER, m.WATER, m.GRASS_W_WATER_2, m.GRASS_S_WATER_2, m.GRASS, m.GRASS],
            [m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST_NE_GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.SAND_NW_GRASS, m.SAND_SE_GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS_N_WATER_2, m.GRASS_NE_WATER_2, m.WATER, m.BRIDGE_VERTICAL, m.WATER, m.GRASS_SW_WATER_2],
            [m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST_SE_GRASS, m.GRASS, m.GRASS, m.SAND_NW_GRASS, m.SAND_N_GRASS, m.SAND_NS_GRASS, m.SAND_SE_GRASS, m.GRASS, m.FOREST_NW_GRASS, m.FOREST_NE_GRASS, m.GRASS, m.GRASS, m.GRASS_S_WATER_2, m.GRASS_N_WATER_2, m.GRASS_E_WATER_2, m.WATER, m.WATER],    
            [m.FOREST, m.FOREST, m.FOREST, m.FOREST_SE_GRASS, m.GRASS, m.GRASS, m.SAND_NW_GRASS, m.SAND, m.SAND_E_GRASS, m.GRASS, m.GRASS, m.FOREST_NW_GRASS, m.FOREST, m.FOREST_E_GRASS, m.GRASS, m.GRASS_E_WATER_2, m.WATER, m.GRASS_SW_WATER_2, m.GRASS_S_WATER_2, m.GRASS_N_WATER_2, m.GRASS_N_WATER_2],
            [m.FOREST_S_GRASS, m.FOREST_S_GRASS, m.FOREST_SE_GRASS, m.GRASS, m.GRASS, m.SAND_NW_GRASS, m.SAND, m.SAND, m.SAND_E_GRASS, m.GRASS, m.GRASS, m.FOREST_W_GRASS, m.FOREST, m.FOREST, m.FOREST_NE_GRASS, m.GRASS, m.GRASS_NE_WATER_2, m.WATER, m.WATER, m.GRASS_SW_WATER_2, m.GRASS],
            [m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.SAND_W_GRASS, m.SAND, m.SAND_S_GRASS, m.SAND_SE_GRASS, m.GRASS, m.FOREST_NW_GRASS, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST_NE_GRASS, m.GRASS, m.GRASS_NE_WATER_2, m.WATER, m.WATER, m.GRASS_W_WATER_2],
            [m.VILLAGE, m.GRASS, m.GRASS, m.GRASS, m.SAND_NW_GRASS, m.SAND_S_GRASS, m.SAND_SE_GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_W_GRASS, m.FOREST, m.FOREST, m.FOREST, m.FOREST_CLEARING_SHADEABBEY, m.FOREST_E_GRASS, m.GRASS, m.GRASS_E_WATER_2, m.WATER, m.WATER, m.GRASS_W_WATER_2],
            [m.GRASS, m.GRASS, m.SAND_NWS_GRASS, m.SAND_NS_GRASS, m.SAND_SE_GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_NW_GRASS, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST_E_GRASS, m.GRASS, m.GRASS, m.GRASS_N_WATER_2, m.GRASS_N_WATER_2, m.GRASS],
            [m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.BUSH_NEWS_GRASS, m.GRASS, m.FOREST_NW_GRASS, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST_CLEARING_HOUSE, m.FOREST, m.FOREST, m.FOREST_NE_GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_NW_GRASS],
            [m.GRASS, m.GRASS, m.GRASS, m.VILLAGE, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_W_GRASS, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST_CLEARING_HOUSE, m.FOREST, m.FOREST_N_GRASS, m.FOREST_N_GRASS, m.FOREST_N_GRASS, m.FOREST],
            [m.VILLAGE, m.GRASS, m.GRASS, m.GRASS, m.GRASS, m.FOREST_NEW_GRASS, m.GRASS, m.GRASS, m.FOREST_W_GRASS, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST, m.FOREST],
            ]

# FOR TESTING:

##### Define Display variables:
##TILESIZE = 32
##MAPWIDTH = 21
##MAPHEIGHT = 21             
##WIN_WIDTH = MAPWIDTH*TILESIZE
##WIN_HEIGHT = MAPHEIGHT*TILESIZE
##DISPLAY = (WIN_WIDTH, WIN_HEIGHT)
##current_map = test_battle
##
### Set Up the Display:
##pygame.init()
##DISPLAYSURF = pygame.display.set_mode(DISPLAY)
##pygame.display.set_caption("Shining Force")
##icon = pygame.image.load('../Assets/icon.png').convert_alpha()
##pygame.display.set_icon(icon)
##
### Display the map:
##for row in range(MAPHEIGHT):
##    for column in range(MAPWIDTH):
##        # Display the map tiles:
##        DISPLAYSURF.blit(m.textures[current_map[row][column]], (column*TILESIZE, row*TILESIZE, TILESIZE, TILESIZE))
##        
### Update the display:
##pygame.display.flip()
##pygame.display.update()
